stateDiagram-v2
    %% Detailed view of INITIALIZATION


    %% Internal transitions

    %% External composites
    state MAINPROCESSING
    state COMPLETION

    %% Transitions to other composites
    initializing --> MAINPROCESSING : initialized