stateDiagram-v2
    %% Detailed view of INITIALIZATION


    %% Internal transitions

    %% External composites
    state MAINLOOP
    state COMPLETION

    %% Transitions to other composites
    initializing --> MAINLOOP : initialized