stateDiagram-v2
    %% Detailed view of COMPLETION

    [*] --> failed
    [*] --> ready
    [*] --> shutdown

    %% Internal transitions

    %% External composites
    state IDLE
    state PROCESSING

    %% Transitions to other composites
    failed --> IDLE : retry_report
    ready --> IDLE : process_next