stateDiagram-v2
    %% Detailed view of IDLE

    [*] --> waiting_for_report

    %% Internal transitions

    %% External composites
    state SUMMARIZING
    state FACT_CHECKING
    state COMPLETED

    %% Transitions to other composites
    waiting_for_report --> SUMMARIZING : new_report