name: "Simple Worker"
initial_state: waiting

states:
  - waiting
  - processing
  - completed

events:
  - new_job
  - job_done

transitions:
  - from: waiting
    to: processing
    event: new_job
    actions:
      - type: check_database_queue
        params:
          job_type: task

  - from: processing
    to: completed
    event: job_done
    actions:
      - type: bash
        params:
          command: "echo Processed {job_id}"
          success: job_done
