stateDiagram-v2
    %% Detailed view of COMPLETION

    [*] --> stopped

    %% Internal transitions

    %% External composites
    state INITIALIZATION
    state MONITORING

    %% Transitions to other composites