stateDiagram-v2
    %% Detailed view of INITIALIZATION


    %% Internal transitions

    %% External composites
    state MONITORING
    state COMPLETION

    %% Transitions to other composites
    initializing --> MONITORING : initialized